export const DEFAULT_MUSIC_TRACKS = [
    { id: "1", name: "Royal Instrumental", url: "" },
    { id: "2", name: "Flute Serenade", url: "" },
    { id: "3", name: "Shehnai Welcome", url: "" },
    { id: "4", name: "Modern Acoustic", url: "" },
    { id: "5", name: "Classical Sitar", url: "" },
    { id: "6", name: "Soft Piano", url: "" },
    { id: "7", name: "Temple Bells", url: "" },
    { id: "8", name: "Joyful Celebration", url: "" },
    { id: "9", name: "Romantic Strings", url: "" },
    { id: "10", name: "Traditional Dhol", url: "" },
    { id: "11", name: "Sunset Melodies", url: "" },
    { id: "12", name: "Divine Chants", url: "" },
    { id: "13", name: "Acoustic Guitar", url: "" },
    { id: "14", name: "Sufi Touch", url: "" },
    { id: "15", name: "Elegant Waltz", url: "" },
    { id: "16", name: "Grand Entrance", url: "" },
    { id: "17", name: "Sangeet Beats", url: "" },
    { id: "18", name: "Peaceful Meditation", url: "" },
    { id: "19", name: "Festive Vibes", url: "" },
    { id: "20", name: "Soulful Journey", url: "" },
];
