export const THEMES = [
    {
        id: 1,
        title: "Laavan",
        themeName: "sikh1",
        category: "Sikh Wedding",
        description: "Elegant Sikh wedding design with sacred aesthetics.",
        image: "/images/invite1.png",
        mobileImage: "/images/1.png",
        demoUrl: "/s/gurpreet-weds-simran-dc8",
    },
    {
        id: 2,
        title: "Royal Palace",
        themeName: "hindu1",
        category: "Hindu Wedding",
        description: "Luxurious theme with grand palace architecture.",
        image: "/images/invite2.png",
        mobileImage: "/images/2.png",
        demoUrl: "/r/aarav-weds-saanvi-cwx",
    },
    {
        id: 3,
        title: "Temple Divine",
        themeName: "hindu2",
        category: "Hindu Wedding",
        description: "Sacred design with traditional temple elements.",
        image: "/images/invite3.png",
        mobileImage: "/images/3.png",
        demoUrl: "/t/aarav-weds-saanvi-frz",
    },
    {
        id: 4,
        title: "Floral Elegance",
        themeName: "hindu3",
        category: "Hindu Wedding",
        description: "Soft and beautiful floral-inspired wedding theme.",
        image: "/images/invite4.png",
        mobileImage: "/images/4.png",
        demoUrl: "/f/ekansh-weds-manika-aw8",
    },
    {
        id: 5,
        title: "Guruji Satsang",
        themeName: "guruji1",
        category: "Guruji Satsang",
        description: "Calm and devotional design for Satsang invites.",
        image: "/images/invite5.png",
        mobileImage: "/images/5.png",
        demoUrl: "/g/guruji-satsang-by-khanna-family-k52",
    },
];

export const getThemeByThemeName = (themeName) => THEMES.find(t => t.themeName === themeName);
